# Generated by Django 3.0 on 2022-12-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenreTitle',
            new_name='TitleGenre',
        ),
    ]
